const translations = {
  pl: {
    Download: "Pobierz CV",
    DownloadLink: "https://gofile.io/d/E8TL3I",
    Contact: "Kontakt",
    AboutMe: "O mnie",
    AboutMeDescription:
      "Jestem absolwentem studiów inżynierskich z rosnącym zainteresowaniem w dziedzinie uczenia maszynowego. Dobrze czuję się pracując w zespole i zawsze jestem zmotywowany do nauki i rozwoju. Dzięki aktywnym udziale w  samorządzie studenckim, zdobyłem doświadczenie w organizacji wydarzeń. W wolnym czasie gram na gitarze w zespole, lubię grać w szachy i uczę się języka japońskiego.",
    Skills: "Umiejętności",
    CriticalThinking: "Krytyczne myślenie",
    Teamwork: "Praca zespołowa",
    Communication: "Komunikacja",
    Creativity: "Kreatywność",
    ProblemSolving: "Rozwiązywanie problemów",
    Experience: "Doświadczenie",
    DateAntrez1: "Październik 2023 - Styczeń 2025",
    Antrez1Description:
      "Opracowywanie, testowanie i wdrażanie rozwiązań programowych do zastosowań medycznych.",
    DateAntrez2: "Lipiec 2023 - Październik 2023",
    Antrez2Description:
      "Pomoc w projektowaniu i tworzeniu komponentów systemu. Zdobycie doświadczenia w programowaniu i integracji systemów.",
    Education: "Edukacja",
    ML: "Machine Learning A-Z Kurs",
    MLDate: "Grudzień 2024 - Obecnie",
    IE: "Magister - Informatyka i Ekonometria",
    UG: "Uniwersytet Gdański",
    UGDate: "Październik 2024 - Obecnie",
    UGProfile: "Specjalizacja: Analiza danych - Big Data",
    ACIR: "Inżynier – Automatyka, Cybernetyka i Robotyka",
    PG: "Politechnika Gdańska",
    PGDate: "Październik 2020 - Marzec 2024",
    PGProfile: "Specjalizacja: Systemy decyzyjne i Robotyka",
    Projects: "Znaczące projekty akademickie",
    AntiPlagiarism: "System antyplagiatowy",
    AntiPlagiarismDescription:
      "System, który wykrywa i zaznacza podobieństwa w treści plików, w tym konwencje nazewnictwa, strukturę, funkcjonalność oraz podobieństwo do kodu wygenerowanego przez chat GPT.",
    NAO: "Nao Robot",
    NAODescription:
      "oprogramowanie umożliwiające robotowi NAO wykonywanie wielu podstawowych poleceń przy jednoczesnej interakcji z użytkownikiem dzięki integracji z chat GPT.",
    Timelapse: "Timelapse",
    TimelapseDescription:
      "Połączono nagrania z terenu kampusu Politechniki Gdańskiej za pomocą OpenCV i usunięto poruszające się obiekty (ludzi, samochody), aby stworzyć efekt opuszczonego kampusu.",
    TechKnowledge: "Wiedza techniczna",
    tech1:
      "Doświadczenie w programowaniu w językach <strong>Python</strong> i <strong>C++</strong>",
    tech2: "Umiejętność przetwarzania danych za pomocą <strong>SQL</strong>",
    tech3:
      "Dobra znajomość tworzenia stron internetowych w <strong>HTML</strong> i <strong>CSS</strong>",
    tech4:
      "Największe doświadczenie w pracy z <strong>Visual Studio Code</strong> i <strong>Pycharm</strong>",
    tech5: "Dobra znajomość systemu <strong>Git</strong>",
  },

  en: {
    Download: "Download CV",
    DownloadLink: "https://gofile.io/d/E8TL3I",
    Contact: "Contact",
    AboutMe: "About Me",
    AboutMeDescription:
      "I am a postgraduate with a growing interest in machine learning and teamwork, always motivated to learn and develop new skills. I have developed coordination and management abilities through active participation in student government. Beyond my academic and professional pursuits, I play guitar in a band, enjoy chess, and am learning Japanese to broaden my cultural and intellectual horizons.",
    Skills: "Skills",
    CriticalThinking: "Critical thinking",
    Teamwork: "Teamwork",
    Communication: "Communication",
    Creativity: "Creativity",
    ProblemSolving: "Problem solving",
    Experience: "Experience",
    DateAntrez1: "October 2023 - January 2025",
    Antrez1Description:
      "Developed, tested, and implemented software solutions for medical applications.",
    DateAntrez2: "July 2023 - October 2023",
    Antrez2Description:
      "Assisted in design and code system components. Gained experience in software development and system integration.",
    Education: "Education",
    ML: "Machine Learning A-Z Course",
    MLDate: "December 2024 - Present",
    IE: "Master's degree - Informatics and Econometrics",
    UG: "University of Gdańsk",
    UGDate: "October 2024 - Present",
    UGProfile: "Profile: Big data analysis",
    ACIR: "Bachelor of Engineering – Automatic Control, Cybernetics and Robotics",
    PG: "Gdańsk University of Technology",
    PGDate: "October 2020 - March 2024",
    PGProfile: "Profile: Decision Systems and Robotics",
    Projects: "Significant Academic Projects ",
    AntiPlagiarism: "Anti-plagiarism System",
    AntiPlagiarismDescription:
      "System that detects and highlights similarities in file content, including naming conventions, structure, functionality, and resemblance to code generated by chat GPT",
    NAO: "Nao Robot",
    NAODescription:
      "Created software enabling the NAO robot to perform multiple basic commands while simultaneously interacting with users via integration with chat GPT.",
    Timelapse: "Timelapse",
    TimelapseDescription:
      "Combined the footage around the GUT campus using OpenCV, and removed moving objects (people, cars) to create an abandoned campus effect.",
    TechKnowledge: "Technical Knowledge",
    tech1:
      "Experience in <strong>Python</strong> and <strong>C++</strong> Software development",
    tech2: "Skilled in data extraction through <strong>SQL</strong>",
    tech3:
      "Good knowledge of <strong>HTML</strong> and <strong>CSS</strong> Web development",
    tech4:
      "Most experienced with <strong>Visual Studio Code</strong> and <strong>Pycharm</strong>",
    tech5: "Good knowledge of <strong>Git</strong>",
  },
};

let currentLang = "en";

function translatePage(lang) {
  document.querySelectorAll("[data-i18n]").forEach((el) => {
    const key = el.getAttribute("data-i18n");
    if (translations[lang][key]) {
      // Zmiana tekstu
      el.innerHTML = translations[lang][key];

      // Jeśli to przycisk pobierania CV – zmień też href
      if (key === "Download") {
        el.setAttribute("href", translations[lang]["DownloadLink"]);
      }
    }
  });
}

document.getElementById("lang-toggle").addEventListener("click", () => {
  currentLang = currentLang === "en" ? "pl" : "en";
  translatePage(currentLang);
  document.getElementById("lang-toggle").textContent =
    currentLang === "en" ? "PL" : "EN";
});

// Initial load
document.addEventListener("DOMContentLoaded", () => {
  translatePage(currentLang);
});
